import type { Metadata, Viewport } from "next";
import "../styles/global.css";
import styles from "../styles/Root.module.css";
import Link from "next/link";
import NavBar from "@/components/NavBar";

export interface I_LayoutProps {
  children: React.ReactNode;
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
};

export const metadata: Metadata = {
  title: "메이플 To Do",
  description: "Generated by create next app",
  icons: {
    icon: "imgs/logo/icons.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={styles.Wrapper}>
        <header className={styles.header}>
          <Link href={"/"} className={styles.Titles}>
            <img src={"imgs/logo/icons.png"} />
            <span>메이플 To Do</span>
          </Link>
          <NavBar />
        </header>
        {children}
      </body>
    </html>
  );
}
